markdown: rdiscount
pygments: true
navigation:
- text: Speakers
  url: /speakers
- text: Workshops
  url: /workshops
- text: Venue
  url: /venue
- text: Sponsors
  url: /sponsors
- text: Contact
  url: /contact
2012navigation:
- text: 
  url: /2012/
- url: /2012/details
  text: Details
- url: /2012/speakers
  text: Speakers
- url: /2012/schedule
  text: Schedule
- url: /2012/sponsors
  text: Sponsors
- url: /2012/location
  text: Location
- url: /2012/feedback-form
  text: Feedback
speakers:
- name: Daniel Fiske
  company: Rightshift
  title: CEO and Founder
- name: Daniel Schauenberg
  company: Etsy
  title: Software Engineer
- name: Mike Jones
  company: Western Cape Labs
  title: Jack of all trades
- name: Miles Ward
  company: Amazon
  title: Evangelist
- name: David Tinker
  company: Brandseye
  title: Title
- name: Neil Blakey-Milner
  company: Facebook
  title: Production Engineer
- name: RI Pienaar
  company: PuppetLabs
  title: Developer
- name: Robert Stuttaford
  company: Cognician
- name: Dave Humby
  company: Nomanini
  title: CTO
- name: Kenny Gryp
  company: Percona
sponsors:
  gold:
    - name: Microsoft Azure
      about: A rock-solid cloud platform for blue-sky thinking
    - name: RightShift
      about: Online Gambling and Casino 
  silver:
    - name: Amazon
    - name: 2Go
    - name: Praekelt
    - name: RSAWeb
  bronze:
    - name: Basho
    - name: Clickatell
    - name: Brandseye
  event:
    - name: Github
    - name: Key Connections
    - name: RSAWeb




