markdown: rdiscount
pygments: true
navigation:
- text: 
  url: 
- url: /details
  text: Details
- url: /speakers
  text: Speakers
- url: /schedule
  text: Schedule
- url: /sponsors
  text: Sponsors
- url: /location
  text: Location
