
quicket_productid: 13990

waiting_list_url: https://docs.google.com/forms/d/1WOB3UD0XMfljzwqoqvqIw36xnuDbPs0RcjZDG5_L_4o/viewform

current_year: 2017
years:
  - 2017
  - 2016
  - 2015
  - 2014
  - 2013

homepage_sections:
  upcoming_conference: false
  tickets_sell: true
  tickets_notify: false
  current_speakers: true
  previous_speakers: false
  sponsors: true
navigation:
  submit: false
